version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    volumes:
      - /var/lib/rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    env_file:
      - .env
  redis:
    image: redis:latest
    container_name: redis
    hostname: redis
    volumes:
      - /var/lib/redis
    ports:
      - '6379:6379'
    command: redis-server --requirepass ${REDIS_PASSWORD}
    env_file:
      - .env
