version: '3.8'
services:
  redis_prod:
    image: redis:latest
    container_name: redis
    hostname: redis
    volumes:
      - /var/lib/redis
    ports:
      - '6379:6379'
    command: redis-server --requirepass ${REDIS_PASSWORD}
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - HOST=${REDIS_HOST}
    restart: always
    env_file:
      - .env

  server:
    build:
      context: ./
      dockerfile: Dockerfile
    image: server_prod
    container_name: server_prod
    ports:
      - '8080:8080'
    restart: always
    depends_on:
      - redis_prod

volumes:
  redis:
    driver: local
