version: '3.8'
services:
  rabbitmq_prod:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    volumes:
      - /var/lib/rabbitmq
    ports:
      - '5672:5672'
    expose:
      - '5672'
    env_file:
      - .env
    networks:
      - backend_network

  redis_prod:
    image: redis:latest
    container_name: redis
    hostname: redis
    volumes:
      - /var/lib/redis
    ports:
      - '6379:6379'
    command: redis-server --requirepass ${REDIS_PASSWORD}
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - HOST=${REDIS_HOST}
    env_file:
      - .env
    networks:
      - backend_network

  server:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: server_prod
    ports:
      - '8081:8080'

    depends_on:
      - rabbitmq_prod
      - redis_prod
    networks:
      - backend_network
networks:
  backend_network:
    driver: bridge

volumes:
  redis:
    driver: local
# networks:
#   cnm-network:
#     internal: true
# restart: on-failure
#   mongodb_container:
#     build: ./mongors
#     restart: always
#     environment:
#       MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
#       MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
#       MONGO_INITDB_DATABASE: ${MONGO_DB}
#       MONGO_REPLICA_SET: ${MONGO_REPLICA_SET}
#       MONOGO_REPLICA_PORT: ${MONGO_REPLICA_PORT}
#     container_name: mongodb
#     ports:
#       - 27017:27017
#     volumes:
#       - mongodb_data_container:/data/db
#     env_file:
#       - .env

# volumes:
#   mongodb_data_container:
#     driver: local
# docker network create cnm-network
# docker network connect cnm-network redis
# docker network connect cnm-network rabbitmq
